//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBookShopService")]
    public interface IBookShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetBooks", ReplyAction="http://tempuri.org/IBookShopService/GetBooksResponse")]
        string[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetBooks", ReplyAction="http://tempuri.org/IBookShopService/GetBooksResponse")]
        System.Threading.Tasks.Task<string[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/RegisterUser", ReplyAction="http://tempuri.org/IBookShopService/RegisterUserResponse")]
        void RegisterUser(string name, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/RegisterUser", ReplyAction="http://tempuri.org/IBookShopService/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(string name, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetBooksByCategory", ReplyAction="http://tempuri.org/IBookShopService/GetBooksByCategoryResponse")]
        string[] GetBooksByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetBooksByCategory", ReplyAction="http://tempuri.org/IBookShopService/GetBooksByCategoryResponse")]
        System.Threading.Tasks.Task<string[]> GetBooksByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetUserInfo", ReplyAction="http://tempuri.org/IBookShopService/GetUserInfoResponse")]
        string GetUserInfo(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetUserInfo", ReplyAction="http://tempuri.org/IBookShopService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<string> GetUserInfoAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetCategories", ReplyAction="http://tempuri.org/IBookShopService/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetCategories", ReplyAction="http://tempuri.org/IBookShopService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/BuyBook", ReplyAction="http://tempuri.org/IBookShopService/BuyBookResponse")]
        void BuyBook(int bookId, int count, int orderId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/BuyBook", ReplyAction="http://tempuri.org/IBookShopService/BuyBookResponse")]
        System.Threading.Tasks.Task BuyBookAsync(int bookId, int count, int orderId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/CheckUserCredentials", ReplyAction="http://tempuri.org/IBookShopService/CheckUserCredentialsResponse")]
        bool CheckUserCredentials(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/CheckUserCredentials", ReplyAction="http://tempuri.org/IBookShopService/CheckUserCredentialsResponse")]
        System.Threading.Tasks.Task<bool> CheckUserCredentialsAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetDbSetByType", ReplyAction="http://tempuri.org/IBookShopService/GetDbSetByTypeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetDbSetByType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/GetDbSetByType", ReplyAction="http://tempuri.org/IBookShopService/GetDbSetByTypeResponse")]
        System.Threading.Tasks.Task<object[]> GetDbSetByTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/ContextSaveChanges", ReplyAction="http://tempuri.org/IBookShopService/ContextSaveChangesResponse")]
        void ContextSaveChanges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShopService/ContextSaveChanges", ReplyAction="http://tempuri.org/IBookShopService/ContextSaveChangesResponse")]
        System.Threading.Tasks.Task ContextSaveChangesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookShopServiceChannel : BLL.ServiceReference.IBookShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookShopServiceClient : System.ServiceModel.ClientBase<BLL.ServiceReference.IBookShopService>, BLL.ServiceReference.IBookShopService {
        
        public BookShopServiceClient() {
        }
        
        public BookShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<string[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public void RegisterUser(string name, string email, string password) {
            base.Channel.RegisterUser(name, email, password);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string name, string email, string password) {
            return base.Channel.RegisterUserAsync(name, email, password);
        }
        
        public string[] GetBooksByCategory(string category) {
            return base.Channel.GetBooksByCategory(category);
        }
        
        public System.Threading.Tasks.Task<string[]> GetBooksByCategoryAsync(string category) {
            return base.Channel.GetBooksByCategoryAsync(category);
        }
        
        public string GetUserInfo(int userId) {
            return base.Channel.GetUserInfo(userId);
        }
        
        public System.Threading.Tasks.Task<string> GetUserInfoAsync(int userId) {
            return base.Channel.GetUserInfoAsync(userId);
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public void BuyBook(int bookId, int count, int orderId, int userId) {
            base.Channel.BuyBook(bookId, count, orderId, userId);
        }
        
        public System.Threading.Tasks.Task BuyBookAsync(int bookId, int count, int orderId, int userId) {
            return base.Channel.BuyBookAsync(bookId, count, orderId, userId);
        }
        
        public bool CheckUserCredentials(string email, string password) {
            return base.Channel.CheckUserCredentials(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserCredentialsAsync(string email, string password) {
            return base.Channel.CheckUserCredentialsAsync(email, password);
        }
        
        public object[] GetDbSetByType(string type) {
            return base.Channel.GetDbSetByType(type);
        }
        
        public System.Threading.Tasks.Task<object[]> GetDbSetByTypeAsync(string type) {
            return base.Channel.GetDbSetByTypeAsync(type);
        }
        
        public void ContextSaveChanges() {
            base.Channel.ContextSaveChanges();
        }
        
        public System.Threading.Tasks.Task ContextSaveChangesAsync() {
            return base.Channel.ContextSaveChangesAsync();
        }
    }
}
